# 1. Arrays

In [ ]:
#https://www.hackerrank.com/challenges/np-arrays/problem

In [4]:
import numpy as np

def arrays(arr):
    
    return(np.array(arr[::-1], float))
    
arr = input("Enter a single line of input containing space separated numbers : ").strip().split(' ')

result = arrays(arr)

print(result)

Enter a single line of input containing space separated numbers : 1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# 2. Shape and Reshape



In [ ]:
# https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [2]:
import numpy as np
l=input("Enter a single line of input containing 9 space separated integers : ").split()
a=np.array(l,int)
a.shape=(3,3)
print(a)

Enter a single line of input containing 9 space separated integers : 1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 3. Transpose and Flatten



In [ ]:
# https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem

Transpose

We can generate the transposition of an array using the tool numpy.transpose.
It will not affect the original array, but it will create a new array.

import numpy
my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print numpy.transpose(my_array)

#Output
[[1 4]
 [2 5]
 [3 6]]

Flatten

The tool flatten creates a copy of the input array flattened to one dimension.

import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print my_array.flatten()

#Output
[1 2 3 4 5 6]

Task

You are given a $ N X M $ integer array matrix with space separated elements $ (N = rows \ and \ M = columns). $
Your task is to print the transpose and flatten results.

In [1]:
import numpy as np
n, m = map(int, input("Enter the first line contains the space separated values of  and M and N : ").split())

storage = np.array([input("Enter the next N lines contains the space separated elements of M columns : ").strip().split() for _ in range(n)], int)
print (storage.transpose())
print (storage.flatten())

Enter the first line contains the space separated values of  and M and N : 2 2
Enter the next N lines contains the space separated elements of M columns : 1 2
Enter the next N lines contains the space separated elements of M columns : 3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# 4. Concatenate

In [2]:
# https://www.hackerrank.com/challenges/np-concatenate/problem

In [3]:
print("Print the concatenated array of size (N+M) X P : ")
import numpy as np
P, N, M = map(int,input("Enter the first line contains space separated integers N, M and P : ").split())
A = np.array([input("The next N lines contains the space separated elements of the P columns : ").split() for _ in range(P)],int)
B = np.array([input("After that, the next M lines contains the space separated elements of the P columns : ").split() for _ in range(N)],int)
print(np .concatenate((A, B), axis = 0))

Print the concatenated array of size (N+M) X P : 
Enter the first line contains space separated integers N, M and P : 4 3 2
The next N lines contains the space separated elements of the P columns : 1 2
The next N lines contains the space separated elements of the P columns : 1 2
The next N lines contains the space separated elements of the P columns : 1 2
The next N lines contains the space separated elements of the P columns : 1 2
After that, the next M lines contains the space separated elements of the P columns : 3 4
After that, the next M lines contains the space separated elements of the P columns : 3 4
After that, the next M lines contains the space separated elements of the P columns : 3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# 5. Zeros and Ones

In [4]:
# https://www.hackerrank.com/challenges/np-zeros-and-ones/problem

In [5]:
import numpy as np

N = tuple(map(int, input("Enter a single line containing the space-separated integers : ").split()))
print(np.zeros(N, int))
print(np.ones(N, int))

Enter a single line containing the space-separated integers : 3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# 6. Eye and Identity



In [6]:
# https://www.hackerrank.com/challenges/np-eye-and-identity/problem

In [7]:
import numpy as np

np.set_printoptions(sign=' ')
print(np.eye(*map(int, input("A single line containing the space separated values of N and M ").split())))

A single line containing the space separated values of N and M : 3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# 7. Array Mathematics



In [8]:
# https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [15]:
import numpy as np
N, M= map(int, input("The first line contains two space separated integers, N and M : ").split())
A = np.array([list(map(int, input("The next N lines contains M space separated integers of array A : ").split())) for i in range(N)])
B = np.array([list(map(int, input("The following N lines contains M space separated integers of array B : ").split())) for i in range(N)])
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A % B)
print(A ** B)

The first line contains two space separated integers, N and M : 1 4
The next N lines contains M space separated integers of array A : 1 2 3 4
The following N lines contains M space separated integers of array B : 5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[ 0.2         0.33333333  0.42857143  0.5       ]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# 8. Floor, Ceil and Rint



In [16]:
# https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem

In [17]:
import numpy as np

np.set_printoptions(sign=' ')

array = np.array(input("A single line of input containing the space separated elements of array A : ").split(),float)

print(np.floor(array))
print(np.ceil(array))
print(np.rint(array))

A single line of input containing the space separated elements of array A : 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# 9. Sum and Prod



In [18]:
# https://www.hackerrank.com/challenges/np-sum-and-prod/problem

In [21]:
import numpy as np

N, M = map(int, input("The first line of input contains space separated values of N and M : ").split())
A = np.array([input("The next N lines contains M space separated integers : ").split() for _ in range(N)], int)
print(np.prod(np.sum(A, axis=0), axis=0))

The first line of input contains space separated values of N and M : 2 2
The next N lines contains M space separated integers : 1 2
The next N lines contains M space separated integers : 3 4
24


# 10. Min and Max



In [22]:
# https://www.hackerrank.com/challenges/np-min-and-max/problem

In [23]:
import numpy as np

N, M = map(int, input("The first line of input contains the space separated values of N and M : ").split())
storage = np.array([input("The next N lines contains M space separated integers : ").split() for _ in range(N)],int)
print(np.max(np.min(storage, axis=1), axis=0))

The first line of input contains the space separated values of N and M : 4 2
The next N lines contains M space separated integers : 2 5
The next N lines contains M space separated integers : 3 7
The next N lines contains M space separated integers : 1 3
The next N lines contains M space separated integers : 4 0
3


# 11. Mean, Var, and Std

In [24]:
# https://www.hackerrank.com/challenges/np-mean-var-and-std/problem

In [12]:
import numpy
n,m = map(int,input("The first line contains the space separated values of N and M : ").split())
ar = []
for i in range(n):
    tmp = list(map(int,input("The next N lines contains M space separated integers : ").split()))
    ar.append(tmp)
np_ar = numpy.array(ar)
print(numpy.mean(np_ar,axis=1))
print(numpy.var(np_ar,axis=0))
print(numpy.std(np_ar,axis=None))

The first line contains the space separated values of N and M : 2 2
The next N lines contains M space separated integers : 1 2
The next N lines contains M space separated integers : 3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# 12. Dot and Cross



In [13]:
# https://www.hackerrank.com/challenges/np-dot-and-cross/problem

In [14]:
import numpy as np

n = int(input("The first line contains the integer N : "))
a = np.array([input("The next N lines contains N space separated integers of array A : ").split() for _ in range(n)], int)
b = np.array([input("The following N lines contains N space separated integers of array B : ").split() for _ in range(n)], int)
print(np.dot(a, b))

The first line contains the integer N : 2
The next N lines contains N space separated integers of array A : 1 2
The next N lines contains N space separated integers of array A : 3 4
The following N lines contains N space separated integers of array B : 1 2
The following N lines contains N space separated integers of array B : 3 4
[[ 7 10]
 [15 22]]


# 13. Inner and Outer



In [15]:
# https://www.hackerrank.com/challenges/np-inner-and-outer/problem

In [20]:
import numpy as np

A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A, B), numpy.outer(A, B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


# 14. Polynomials



In [ ]:
# https://www.hackerrank.com/challenges/np-polynomials/problem

In [19]:
import numpy as np

poly = [float(x) for x in input("The first line contains the space separated value of the coefficients in P : ").split()]
x = float(input("The second line contains the value of x : "))

print(np.polyval(poly, x))

The first line contains the space separated value of the coefficients in P : 1.1 2 3
The second line contains the value of x : 0
3.0


# 15. Linear Algebra



In [17]:
# https://www.hackerrank.com/challenges/np-linear-algebra/problem

In [21]:
import numpy as np
N = int(input("The first line contains the integer N : "))
A = np.array([input("The next N lines contains the N space separated elements of array A : ").split() for _ in range(N)], float)
print(round(np.linalg.det(A),2))

The first line contains the integer N : 2
The next N lines contains the N space separated elements of array A : 1.1 1.1
The next N lines contains the N space separated elements of array A : 1.1 1.1
0.0
